### ISSUE TITLE
How do you run KioskAssistant?

### ISSUE THREAD

**Issue by suryboom** [florinDNL/KioskAssistant#1]
I was able to download the git, but I am unable to run the project.

How does one run KioskAssistant?

**Comment by florinDNL** [comment]
Hello, if you just want to execute the program, you need to download and extract KioskAssistant.zip from the releases: https://github.com/florinDNL/KioskAssistant/releases/tag/v1.0.7
![image](https://github.com/user-attachments/assets/84ef3936-221f-4e4a-9779-a7371d3baa57)

It needs .NET Desktop Runtime 7 to run so install that as well: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.4-windows-x64-installer

If you want to compile it yourself, open the project in Visual Studio - if that doesn't work, please specify the error.

**Comment by suryboom** [comment]
![IMG_1903](https://github.com/user-attachments/assets/d8430dbf-4250-4b00-9c94-d626d96c11f2)

This is what I get when I run it from Visual Studio.

**Comment by suryboom** [comment]
Is there any easier way to run this - without having to use Visual Studio?

**Comment by florinDNL** [comment]
> ![IMG_1903](https://private-user-images.githubusercontent.com/62725467/377239245-d8430dbf-4250-4b00-9c94-d626d96c11f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODI0MjUsIm5iZiI6MTcyOTE4MjEyNSwicGF0aCI6Ii82MjcyNTQ2Ny8zNzcyMzkyNDUtZDg0MzBkYmYtNDI1MC00YjAwLTljOTQtZDYyNmQ5NmMxMWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE2MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OGZiYzk5NTIwNjUzNTMwNTIzNzk3ZGU2ZjJmMGVkMGJmOTYwYjQyMjk0NmFjNTlkNzI5ZWM4ZTRmZjY1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.poubziBqtzM3g9cEixAP_hm-lL3kVa1yizkrv5duiog)
> 
> This is what I get when I run it from Visual Studio.

Those errors are the missing NuGet packages, you can add them to the solution manually in Visual Studio.

> Is there any easier way to run this - without having to use Visual Studio?

Like I said, if you just want to execute the program, you can download the pre-compiled binaries directly and run the .exe file. Download here: https://github.com/florinDNL/KioskAssistant/releases/download/v1.0.7/KioskAssistant.zip

To be able to run it, install .NET Desktop Runtime 7: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.4-windows-x64-installer

**Comment by suryboom** [comment]
Ohhh I downloaded the master - that's why i didn't see the EXE.

This is amazing!!! Thank you so much for this! It is game changer!
